### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kirill-21** [danielkrupinski/OsirisInventory#1]
Allow applying skins from inventory during the match

**Comment by danielkrupinski** [comment]
Do you mean that you're not able to change the equipment during a competitive match?

**Comment by kirill-21** [comment]
> Do you mean that you're not able to change the equipment during a competitive match?

yes

**Comment by Frouk3** [comment]
since client thinks that skins added from inventory changer are real, client won't let you to change skins
