### ISSUE TITLE
How can u add new skins?

### ISSUE THREAD

**Issue by monkeythatprograms** [danielkrupinski/OsirisInventory#15]
Some skins are not there. Anyone knows how to add?

**Comment by danielkrupinski** [comment]
Which skins are missing?

**Comment by monkeythatprograms** [comment]
https://csgostash.com/skin/1396/SSG-08-Death-Strike, theres prob some more but i this one is not in

**Comment by monkeythatprograms** [comment]
btw @danielkrupinski is there a autoload cfg thing?

**Comment by danielkrupinski** [comment]
I've checked and **SSG 08 Death Strike** is available.
